# Generated by Django 5.2.17 on 2026-09-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_order_orderitem_ticket_tickettier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
    ]
