# Generated by Django 5.2.17 on 2026-09-28 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('category', models.CharField(choices=[('Culinary & Wine', 'Culinary & Wine'), ('Architecture & Design', 'Architecture & Design'), ('Fine Arts & Craft', 'Fine Arts & Craft'), ('Music & Performance', 'Music & Performance'), ('Literature & Thought', 'Literature & Thought'), ('Gatherings & Salons', 'Gatherings & Salons')], max_length=60)),
                ('description', models.TextField()),
                ('full_content', models.TextField(blank=True, default='')),
                ('date_display', models.CharField(max_length=120)),
                ('iso_date', models.DateField()),
                ('time_display', models.CharField(max_length=120)),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_address', models.CharField(blank=True, default='', max_length=255)),
                ('venue_city', models.CharField(blank=True, default='', max_length=120)),
                ('venue_neighborhood', models.CharField(blank=True, default='', max_length=120)),
                ('venue_map_note', models.TextField(blank=True, default='')),
                ('venue_lat', models.FloatField(blank=True, null=True)),
                ('venue_lng', models.FloatField(blank=True, null=True)),
                ('starting_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('attendee_count', models.PositiveIntegerField(default=0)),
                ('artwork_image', models.ImageField(blank=True, null=True, upload_to='gatherings/artwork/')),
                ('artwork_url', models.CharField(blank=True, default='', max_length=500)),
                ('host_name', models.CharField(blank=True, default='', max_length=120)),
                ('host_role', models.CharField(blank=True, default='', max_length=120)),
                ('host_avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('host_bio', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('sold_out', 'Sold Out')], default='published', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('curator_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_gatherings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='gatherings.gathering')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('available', models.PositiveIntegerField(default=50)),
                ('perks', models.JSONField(blank=True, default=list)),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='gatherings.gathering')),
            ],
        ),
    ]
