# Generated by Django 5.2.17 on 2026-09-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaitem',
            options={'ordering': ['order']},
        ),
    ]
