# Generated by Django 5.2.17 on 2026-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0002_alter_agendaitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='category',
            field=models.CharField(choices=[('Sports & Outdoors', 'Sports & Outdoors'), ('Entertainment & Music', 'Entertainment & Music'), ('Business & Entrepreneurship', 'Business & Entrepreneurship'), ('Tech & Innovation', 'Tech & Innovation'), ('Education & Career', 'Education & Career'), ('Arts & Culture', 'Arts & Culture'), ('Social Impact & Community', 'Social Impact & Community'), ('Political', 'Political'), ('Others', 'Others')], max_length=60),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
