# Generated by Django 5.2.17 on 2026-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patron', 'Attendee'), ('curator', 'Organizer')], default='patron', max_length=20),
        ),
    ]
