# Generated by Django 5.2.17 on 2026-09-28 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatherings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('tier_name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attendee_name', models.CharField(max_length=120)),
                ('attendee_email', models.EmailField(max_length=254)),
                ('ticket_code', models.CharField(max_length=60, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit / Debit Card'), ('complimentary', 'Curator Invitation')], default='card', max_length=20)),
                ('mpesa_phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('mpesa_receipt_number', models.CharField(blank=True, default='', max_length=50)),
                ('total_in_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gatherings.gathering')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='gatherings.gathering')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gathering')},
            },
        ),
    ]
