# Generated by Django 5.2.17 on 2026-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_booking_options_booking_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Credit / Debit Card'), ('complimentary', 'Organizer Invitation'), ('free', 'Free Entry')], default='card', max_length=20),
        ),
    ]
